#!/bin/bash

# update packages
sudo apt update
sudo apt install -y llvm-11
sudo LLVM_CONFIG=llvm-config-11 python -m pip install --upgrade timezonefinder[numba] gpsd-py3

sudo python /usr/local/bin/getTz.py
