#!/bin/bash

# update repo
git pull

# install dependencies
sudo apt update
sudo apt -y install pigpiod gpsd gpsd-clients gpsd-tools llvm-11
sudo LLVM_CONFIG=llvm-config-11 python -m pip install --upgrade timezonefinder[numba] gpsd-py3 RPi.GPIO pigpio

# build pps driver
gcc -o pps-out pps.c -lpigpio

# copy scripts to bin directory
sudo cp nixieDriver nixieDriver.py getTz getTz.py pps-out /usr/local/bin


# link timezone setting script to cron and init
sudo ln -s /usr/local/bin/getTz /etc/cron.hourly/
sudo ln -s /usr/local/bin/getTz /etc/init.d/

# link the nixieDriver to init.d
sudo ln -s /usr/local/bin/nixieDriver /etc/init.d/
